carritos/urls.py
from django.urls import path
from . import views

app_name = 'carritos'

urlpatterns = [
    path('', views.carro, name='carrito'),
    path('agregar', views.add, name='add')
]

natural_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from . import views
from productos.views import ProductoListaView



urlpatterns = [
    #path('',  views.index, name= 'index'),
    #utilizar la clase como una vista
    path('',  ProductoListaView.as_view(), name= 'index'),
    path('usuarios/login',  views.login_vista, name= 'login'),
    path('usuarios/logout',  views.logout_vista, name= 'logout'),
    path('usuarios/registro',  views.registro, name= 'registro'),
    path('inventario/inventario',  views.inventario, name= 'inventario'),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('carrito/', include('carritos.urls'))
]

#importante para ver las imagenes en el template

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{titulo_empresa}}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/1d766fd40f.js" crossorigin="anonymous"></script>   
</head>

<body>
    <div>
        <div>
            {% include 'navbar.html' %}
        </div>
        <div class="container">
            {% include 'message.html' %}
            <div class="row">
                {% block contenido %}
                {% endblock%}
            </div>
        </div>
    </div>





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>




<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
    integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
    crossorigin="anonymous"></script>

    

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
    integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
    crossorigin="anonymous"></script>

</html>

<!--

/*
  _                    , ,   _____  
 | |     : :          ()()  (  __ |              
 | |      _       __   | |   \ \ \|          
 | |   :/ _ \  :/ _ \| | | :  \ \        
 | |   | | | | | || | || ||\_\ \ \      
 | || || | | | | || | || ||______,)      
 |    / \ _ / , \_  | ||_|              
 | _ /         ___| |                      
              |     |  
  Desarrollado por Logi is  
*/

-->

templates/index.html
{% extends 'Base.html' %}

{% block contenido %}




<div class="col">
    <h4 class="tect-center">{{mensaje}}</h4>
    
    {% include 'productos/snippets/buscador.html' with Producto=object %}
        <div class="row">
            {% for object in Productos %}
            <div class="col-3 mt-5">
                {% include 'productos/snippets/producto_maquetado.html' with Producto=object %}
            </div>
            {% endfor %}
        </div>
</div>

{% endblock %}




<!--

/*
  _                    , ,   _____  
 | |     : :          ()()  (  __ |              
 | |      _       __   | |   \ \ \|          
 | |   :/ _ \  :/ _ \| | | :  \ \        
 | |   | | | | | || | || ||\_\ \ \      
 | || || | | | | || | || ||______,)      
 |    / \ _ / , \_  | ||_|              
 | _ /         ___| |                      
              |     |  
  Desarrollado por Logi is  
*/

-->

templates/message.html
{% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags == 'success' %} alert-success {%else%} alert-danger {% endif %}">
    <button type="button" class="close" data-dismiss="alert">x</button>
    {{ message }}
</div>
{% endfor %}
{% endif %}


<!--

/*
  _                    , ,   _____  
 | |     : :          ()()  (  __ |              
 | |      _       __   | |   \ \ \|          
 | |   :/ _ \  :/ _ \| | | :  \ \        
 | |   | | | | | || | || ||\_\ \ \      
 | || || | | | | || | || ||______,)      
 |    / \ _ / , \_  | ||_|              
 | _ /         ___| |                      
              |     |  
  Desarrollado por Logi is  
*/

-->

templates/navbar.html
{% url 'inventario' as inventario %}
{% url 'login' as login %}
{% url 'registro' as registro %}
{% url 'logout' as logout %}
{% url 'carritos:carrito' as carrito %}



<nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">



      <a href="{% url 'index' %}" class="navbar-brand">  Bright Natural Star {{ request.path }}   </a>

      <ul class="navbar-nav">
        <li class="nav-item {% if request.path == carrito %} active {% endif %} ">
          <a class="nav-link"    href="{{ carrito }}">Mi Carrito<span class="fas fa-shopping-cart"></span></a>
        </li>
      </ul>



      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>



      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">Menú</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">

          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            {% if user.is_authenticated  %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == inventario %}active {% endif %}" aria-current="page" href="{{ inventario }}">Inventario</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == logout %}active {% endif %}" href="{{ logout }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link {% if request.path == login %}active {% endif %}" href="{{ login }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == registro %}active {% endif %}" href="{{ registro }}">Registro</a>
            </li>
            {% endif %}
          </ul>
          <!--<form class="d-flex mt-3" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-success" type="submit">Search</button>
          </form>-->
        </div>
      </div>
    </div>
  </nav>




<!--

/*
  _                    , ,   _____  
 | |     : :          ()()  (  __ |              
 | |      _       __   | |   \ \ \|          
 | |   :/ _ \  :/ _ \| | | :  \ \        
 | |   | | | | | || | || ||\_\ \ \      
 | || || | | | | || | || ||______,)      
 |    / \ _ / , \_  | ||_|              
 | _ /         ___| |                      
              |     |  
  Desarrollado por Logi is  
*/

-->